# required
name = "Dummy Dude"
img = "dummy.jpg"
bio = "Dummy bio stuff bla"
url = "http://somewebsite.whatever/"

# optional (full url including http://, except for email)
facebook = ""
googleplus = ""
twitter = ""
linkedin = ""
email = ""
instagram = ""
pintrest = ""
twitch = ""
steam = ""
reddit = ""